id: IE974193A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:50:11+00:00'
last_modified: '2022-06-10T10:51:06.560445+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN412
  title: ཞྭ་དམར་དྲུག་པ་ཆོས་ཀྱི་དབང་ཕྱུག་གི་རྟོགས་པ་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E4D:
      image_group_id: I3CN2853
      title: ''
      total_pages: 378
      order: 1
      base_file: 4E4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
